host: roundseed.com
base_url: "http://roundseed.com"
blog_url: "http://blog.roundseed.com"
email_contact: mat@fogventures.com
email_payments: mat@fogventures.com
email_projects: mat@fogventures.com
email_system: mat@fogventures.com
email_no_reply: mat@fogventures.com

facebook_url: "http://facebook.com/roundseed"
facebook_app_id: 152699881511667

twitter_username: "@roundseed"

mailchimp_url: "http://fogventures.us1.list-manage.com/subscribe/post?u=f36233d353dcb0dff78fa2882&amp;id=795186bca6"

